-- Autor: Gianfranco Pupiales
-- Script de creación de base de datos AskMeInformMe

-- Creación de la tabla Preguntas
CREATE TABLE Preguntas
(
    ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Texto      VARCHAR2(255) NOT NULL,
    Dificultad VARCHAR2(50),
    Categoria  VARCHAR2(50)
);

-- Creación de la tabla Opciones con clave foránea referenciando Preguntas
CREATE TABLE Opciones
(
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Pregunta_ID NUMBER NOT NULL,
    Texto       VARCHAR2(255) NOT NULL,
    Es_Correcta NUMBER(1) DEFAULT 0 CHECK (Es_Correcta IN (0, 1)),
    CONSTRAINT fk_pregunta FOREIGN KEY (Pregunta_ID) REFERENCES Preguntas (ID)
);

-- Inserción de datos en la tabla Preguntas y Opciones
-- Pregunta 1
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Cuál es el nombre del villano principal en la película "El Rey León"?',
        'Fácil',
        'Películas');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del villano principal en la película "El Rey León"?'),
        'Scar',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del villano principal en la película "El Rey León"?'),
        'Mufasa',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del villano principal en la película "El Rey León"?'),
        'Simba',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del villano principal en la película "El Rey León"?'),
        'Timón',
        0);

-- Pregunta 2
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Qué banda lanzó el álbum "Abbey Road"?',
        'Fácil',
        'Música');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda lanzó el álbum "Abbey Road"?'),
        'The Beatles',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda lanzó el álbum "Abbey Road"?'),
        'The Rolling Stones',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda lanzó el álbum "Abbey Road"?'),
        'The Who',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda lanzó el álbum "Abbey Road"?'),
        'Led Zeppelin',
        0);

-- Pregunta 3
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Cuál es el nombre del personaje principal en el videojuego "The Legend of Zelda"?',
        'Fácil',
        'Juegos');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del personaje principal en el videojuego "The Legend of Zelda"?'),
        'Link',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del personaje principal en el videojuego "The Legend of Zelda"?'),
        'Zelda',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del personaje principal en el videojuego "The Legend of Zelda"?'),
        'Ganon',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del personaje principal en el videojuego "The Legend of Zelda"?'),
        'Navi',
        0);

-- Pregunta 4
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Quién pintó "La noche estrellada"?',
        'Fácil',
        'Arte');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Quién pintó "La noche estrellada"?'),
        'Vincent van Gogh',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Quién pintó "La noche estrellada"?'),
        'Pablo Picasso',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Quién pintó "La noche estrellada"?'),
        'Claude Monet',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Quién pintó "La noche estrellada"?'),
        'Leonardo da Vinci',
        0);

-- Pregunta 5
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Cuál es el nombre del director de la película "Inception"?',
        'Media',
        'Películas');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del director de la película "Inception"?'),
        'Christopher Nolan',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del director de la película "Inception"?'),
        'Steven Spielberg',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del director de la película "Inception"?'),
        'Martin Scorsese',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del director de la película "Inception"?'),
        'Quentin Tarantino',
        0);

-- Pregunta 6
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿En qué año se lanzó el videojuego "Super Mario Bros."?',
        'Media',
        'Juegos');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿En qué año se lanzó el videojuego "Super Mario Bros."?'),
        '1985',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿En qué año se lanzó el videojuego "Super Mario Bros."?'),
        '1980',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿En qué año se lanzó el videojuego "Super Mario Bros."?'),
        '1990',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿En qué año se lanzó el videojuego "Super Mario Bros."?'),
        '1988',
        0);

-- Pregunta 7
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Cuál es el nombre de la famosa escultura creada por Michelangelo?',
        'Fácil',
        'Arte');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre de la famosa escultura creada por Michelangelo?'),
        'David',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre de la famosa escultura creada por Michelangelo?'),
        'La Piedad',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre de la famosa escultura creada por Michelangelo?'),
        'Moisés',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre de la famosa escultura creada por Michelangelo?'),
        'La Creación de Adán',
        0);

-- Pregunta 8
INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Qué banda escribió la canción "Bohemian Rhapsody"?',
        'Fácil',
        'Música');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda escribió la canción "Bohemian Rhapsody"?'),
        'Queen',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda escribió la canción "Bohemian Rhapsody"?'),
        'Pink Floyd',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda escribió la canción "Bohemian Rhapsody"?'),
        'The Doors',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda escribió la canción "Bohemian Rhapsody"?'),
        'AC/DC',
        0);

INSERT INTO Preguntas (Texto, Dificultad, Categoria)
VALUES ('¿Cuál es el principio de superposición en mecánica cuántica?',
        'Difícil',
        'Ciencia');

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el principio de superposición en mecánica cuántica?'),
        'Una partícula puede estar en dos o más estados cuánticos simultáneamente hasta que se realice una medición.',
        1);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el principio de superposición en mecánica cuántica?'),
        'Las partículas siempre se encuentran en un estado definido.',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el principio de superposición en mecánica cuántica?'),
        'La superposición solo ocurre en sistemas muy grandes.',
        0);

INSERT INTO Opciones (Pregunta_ID, Texto, Es_Correcta)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el principio de superposición en mecánica cuántica?'),
        'La superposición es la razón por la que la gravedad es más débil que las otras fuerzas fundamentales.',
        0);

-- Commit de los datos insertados
commit;

-- Creación de la tabla Usuarios
CREATE TABLE Usuarios
(
    ID         NUMBER PRIMARY KEY,
    Nombre     VARCHAR2(100),
    RutaImagen VARCHAR2(255)
);

-- Creación de la secuencia para la tabla Usuarios
CREATE SEQUENCE usuarios_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Creación del trigger para la tabla Usuarios
CREATE
OR REPLACE TRIGGER trg_usuarios_id BEFORE
INSERT
  ON Usuarios FOR EACH ROW
BEGIN IF
:NEW.ID IS NULL THEN
SELECT usuarios_seq.NEXTVAL
INTO :NEW.ID
FROM
    dual;

END IF;

END;

/ -- Creación de la tabla Puntajes
CREATE TABLE Puntajes
(
    ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Usuario_ID   NUMBER,
    Puntaje      NUMBER,
    Tiempo_Total NUMBER,
    FOREIGN KEY (Usuario_ID) REFERENCES Usuarios (ID),
    CONSTRAINT UC_Puntaje UNIQUE (Usuario_ID, Puntaje, Tiempo_Total)
);

-- Creación de la tabla DatosCuriosos
CREATE TABLE DatosCuriosos
(
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Pregunta_ID NUMBER NOT NULL,
    Texto       VARCHAR2(255) NOT NULL,
    Enlace1     VARCHAR2(255),
    Enlace2     VARCHAR2(255),
    Enlace3     VARCHAR2(255),
    CONSTRAINT fk_pregunta_curiosa FOREIGN KEY (Pregunta_ID) REFERENCES Preguntas (ID)
);

-- Inserción de datos en la tabla DatosCuriosos
-- Pregunta 1
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del villano principal en la película "El Rey León"?'),
        'Scar fue inspirado en personajes de Shakespeare, especialmente de "Hamlet".',
        'https://www.disneyplus.com/es-ec/movies/el-rey-leon/1HqwiEcje6Nj',
        'https://www.disneyplus.com/es-ec/movies/el-rey-leon/gDBvSe4GpZPD',
        'https://www.disneyplus.com/es-ec/movies/el-rey-leon-2-el-reino-de-simba/7EMejJ1F00Pn');

-- Pregunta 2
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda lanzó el álbum "Abbey Road"?'),
        'El famoso paso de cebra en la portada de "Abbey Road" se encuentra en Londres y es un sitio turístico popular.',
        'https://open.spotify.com/intl-es/album/0ETFjACtuP2ADo6LFhL6HN',
        'https://www.deezer.com/es/album/12047952',
        'https://music.apple.com/es/album/abbey-road-2019-mix/1474815798');

-- Pregunta 3
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del personaje principal en el videojuego "The Legend of Zelda"?'),
        'El nombre del personaje principal, Link, fue elegido para representar la conexión entre el jugador y el juego.',
        'https://www.nintendo.com/es-mx/store/products/the-legend-of-zelda-breath-of-the-wild-switch/',
        'https://www.amazon.es/Legend-Zelda-Breath-Wild/dp/B01MZ977QM',
        'https://www.nintendo.com/es-es/Juegos/Juegos-de-Wii-U/The-Legend-of-Zelda-Twilight-Princess-HD-1082222.html');

-- Pregunta 4
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Quién pintó "La noche estrellada"?'),
        'Vincent van Gogh pintó "La noche estrellada" mientras estaba en un asilo en Saint-Rémy-de-Provence, Francia.',
        'https://historia-arte.com/obras/noche-estrellada-van-gogh',
        'https://www.todocuadros.com/products/van-gogh-noche-estrellada',
        'https://www.bricks.com.ec/products/vincent-van-gogh-la-noche-estrellada');

-- Pregunta 5
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre del director de la película "Inception"?'),
        'Christopher Nolan es conocido por sus complejas narrativas y el uso de efectos prácticos en lugar de CGI.',
        'https://www.max.com/ec/es/movies/el-origen/14552c93-d318-4563-a00b-343df7e35d0b',
        'https://tv.apple.com/mx/movie/el-origen/umc.cmc.6loas01ow0w4lkatxxloz7a6e?playableId=tvs.sbd.9001%3A408813963',
        'https://www.primevideo.com/-/es/detail/0HBUB1JMA08CJWY8V76RCRPTSP/ref=atv_dl_rdr');

-- Pregunta 6
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿En qué año se lanzó el videojuego "Super Mario Bros."?'),
        '"Super Mario Bros." fue lanzado para la Nintendo Entertainment System (NES) y revolucionó la industria de los videojuegos.',
        'https://www.amazon.com/-/es/Super-Mario-Bros/dp/B000FDE058',
        'https://www.amazon.com/-/es/Super-Mario-Bros-Deluxe-Nintendo-Switch/dp/B07HCZ7LPW',
        'https://juegodigitalecuador.com/productos/new-super-mario-bros-u-deluxe-nintendo-switch');

-- Pregunta 7
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el nombre de la famosa escultura creada por Michelangelo?'),
        'La escultura de "David" es famosa por su detalle anatómico y fue tallada en mármol entre 1501 y 1504.',
        'https://historia-arte.com/obras/el-david-de-miguel-angel',
        'https://www.amazon.com/-/es/Escultura-estatua-David-Miguel-grande/dp/B00FZRYE1E',
        'https://www.culturagenial.com/es/escultura-david-de-miguel-angel/');

-- Pregunta 8
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Qué banda escribió la canción "Bohemian Rhapsody"?'),
        '"Bohemian Rhapsody" de Queen no tiene estribillo y es conocida por su estructura inusual y su mezcla de géneros.',
        'https://open.spotify.com/intl-es/track/3z8h0TU7ReDPLIbEnYhWZb',
        'https://music.apple.com/es/album/bohemian-rhapsody/1440821736?i=1440821738',
        'https://www.deezer.com/search/Bohemian%20Rhapsody');

-- Pregunta 9
INSERT INTO DatosCuriosos (Pregunta_ID, Texto, Enlace1, Enlace2, Enlace3)
VALUES ((SELECT ID
         FROM Preguntas
         WHERE Texto = '¿Cuál es el principio de superposición en mecánica cuántica?'),
        'El principio de superposición es fundamental en la mecánica cuántica y es clave para el funcionamiento de los computadores cuánticos.',
        'https://www.mrbooks.com/9788496746817/gatos-suenan-con-fisica-cuantica-y-los-perros',
        'https://www.planetadelibros.com.ec/libro-brevisima-historia-del-tiempo/317920',
        'https://www.casadellibro.com/libro-introduccion-a-la-mecanica-cuantica/9786071601766/2128267');

-- Commit de los datos insertados
commit